version: '3.8'

services:
  tournament-manager:
    build: .
    container_name: tournament-manager
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      # Persistent volume for tournament data
      - tournament-data:/app/server/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/api/tournaments"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  tournament-data:
    driver: local
